### ISSUE TITLE
tinyfiles.h wrong defines usage

### ISSUE THREAD

**Issue by shinyclaw** [RandyGaul/tinyheaders#59]
In line 115:

#elif TF_PLATFORM == TF_MAC || TN_PLATFORM == TN_UNIX

should be:

#elif TF_PLATFORM == TF_MAC || TF_PLATFORM == TF_UNIX

Same in line 278 and 345

**Comment by RandyGaul** [comment]
Fixed!

**Comment by shinyclaw** [comment]
Still wrong defines are used :) Look at lines:

139: #elif TF_PLATFORM == TF_MAC || TF_PLATFORM == TN_UNIX - TN_UNIX should be TF_UNIX
342: #elif TF_PLATFORM == TF_MAC || TN_PLATFORM == TN_UNIX - TN should be TF

**Comment by molguin92** [comment]
I've submitted a pull request fixing this ( #61 ), since I had the same problem :)

**Comment by RandyGaul** [comment]
@molguin92 Thanks a bunch!
